package org.codegen.metadata.constants;

public enum LiteralType {
    VAR_NAME,VAR_REF,METHOD_NAME,CALLER_NAME,ARGUMENT_NAME,CLASS_LEVEL_FIELD_NAME, OPERAND,CONSTRUCTOR_TYPE_NAME,ARGUMENT_AS_EXPRESSION
}
