package org.codegen.metadata.constants;

public enum STATEMENTTYPE {
    VARIABLE_DECLARATION,
    OBJECT_CREATION,
    IF_CONDITION,
    IF_ELSE_CONDITION,
    IF_ELSEIF_ELSE_CONDITION,
    LOOP,
    METHOD_CALL,
    ASSIGNMENT,
    LOG,
    EXCEPTION_BLOCK,
    RETURN_STATEMENT,
    CONSTRUCTOR_CALL,
    SETTER_STATEMENT,
    SUPER_CALL,
    TODO

}
