package org.codegen.metadata.constants;

public enum VariableType {
    VOID,BOOLEAN,BYTE,SHORT,CHAR,INT,LONG,DOUBLE,FLOAT,STRING,USER_DEFINED,NULL,BIGDECIMAL,ARRAYLIST,HASHMAP,HASHSET,TREESET,CLASS,ENUM ;
}
