package org.componentgen.templates.builder.constants;

public enum COMPONENTTYPE {
    WEB_PACKAGE,
    SERVICE_PACKAGE,
    CONTROLLER ,
    METHOD ,
    WEB_REQUEST ,
    WEB_RESPONSE,
    SERVICE_INTERFACE,
    SERVICE_IMPL,
    SERVICE_REQUEST,
    SERVICE_RESPONSE ,
    WEB_REQUEST_DATA,
    WEB_REQUEST_ATTRIBUTES,
    WEB_RESPONSE_DATA,
    WEB_RESPONSE_ATTRIBUTES,
    SERVICE_RESPONSE_ATTRIBUTES,
    COMMAND_RESPONSE,
    EVENT,
    EVENT_LISTENER,
    EVENT_STORE,
    EVENT_STORE_IMPL,
    EVENT_STORE_REQUEST,
    EVENT_STORE_RESPONSE,
    COMMAND,
    GATEWAY_PACKAGE,
    EXCEPTION_HANDLER
}
